### ISSUE TITLE
request for test data for "subset_and_pad_adata" function in preprocessing.py

### ISSUE THREAD

**Issue by bkinnersley** [LungCellAtlas/HLCA_reproducibility#13]
Hello,

Thanks for such a useful repository! I was directed here by example commands to compare user data to a reference GBM atlas using scArches (https://zenodo.org/records/6962901). I am trying to understand the function mentioned in the example commands of the previously-linked dataset "subset_and_pad_adata" which is in preprocessing.py (https://github.com/LungCellAtlas/HLCA_reproducibility/blob/main/scripts/preprocessing.py). 

Would it be possible to provide example "gene_set" and "adata" input files to test this function? e.g. those commented out in the function "/storage/groups/ml01/workspace/hlca_lisa.sikkema_malte.luecken/genes_for_mapping.csv" and "/storage/groups/ml01/workspace/hlca_lisa.sikkema_malte.luecken/ready/adams.h5ad"

Thanks very much

Best wishes

Ben

**Comment by LisaSikkema** [comment]
Thanks @bkinnersley ! 
I would actually advise you to look at the most up-to-date HLCA mapping tutorial, which is now part of scArches:
https://github.com/theislab/scarches/blob/hlca_tutorial_improvements/notebooks/hlca_map_classify.ipynb
That also downloads an example dataset file to test with, and should have all further necessary files either in the repo or also downloaded within the notebook.
 
(The link to the tutorial also be found on the [HLCA landing page](https://github.com/LungCellAtlas/HLCA))

Let me know if that helps!

**Comment by LisaSikkema** [comment]
I'll close this issue now, feel free to re-open if necessary
