### ISSUE TITLE
Request for batch corrected data

### ISSUE THREAD

**Issue by annaKett** [LungCellAtlas/HLCA_reproducibility#14]
Hello all,

thank you lots for providing the notebooks!
I am currently using the HLCA core for a project on pseudo time inference and need to correct the data for batch effects before processing it.
Since I do not have a GPU, I wondered if it might be possible for you to provide the batch corrected data, if available, (not only the PCA embedding) (as per notebook 05_scANVI_integration.ipynb, with "../../data/HLCA_core_h5ads/HLCA_v1_intermediates/LCA_Bano_Barb_Jain_Kras_Lafy_Meye_Mish_MishBud_Nawi_Seib_Teic_log1p.h5ad" as input (which should be the adata.X layer of the .h5ad that I can download from your download center, if I am not confusing anything).

Thank you,
best
-Anna

**Comment by LisaSikkema** [comment]
Hey Anna, so sorry for the late response, somehow I didn't see or forgot about the notification... 
The batch-corrected data is actually the 30-dimensional scANVI embedding that is included in the cellxgene object (together with the counts). You can also download the embedding only (without counts, so much lighter) from zenodo. All relevant links are on the HLCA landing page: https://github.com/LungCellAtlas/HLCA. Let me know if you need anything else!

**Comment by annaKett** [comment]
Hi Lisa,
thank you for your reply! :)
Is there a possibility to get a batch corrected expression matrix (with the initial number of features)?
Some background information: I need to apply metacells clustering to the data and infer pseudotime from the metacells in a subsequent step (with monocle or diffusion pseudo time). Lastly, I want to apply a GRN inference algorithm to the data.
Thank you lots for your help!

**Comment by LisaSikkema** [comment]
Hi Anna,

We don't have a batch-corrected count matrix unfortunately. Correcting the expression matrix is a very non-trivial task, and the methods we tested that did perform correction at the count level performed quite a lot worse in our integration benchmark (you can see the results in the paper). That's how we ended up working only with a batch-corrected low-dimensional embedding. For any gene-level analysis, we tried to account for batch in other ways, e.g. by including it as an extra covariate during modeling, which is also not ideal but it's the best we could come up with.

**Comment by annaKett** [comment]
Hi Lisa,
thank you for your reply! :)
