### ISSUE TITLE
Request for non-SCANVI normalized data

### ISSUE THREAD

**Issue by annaKett** [LungCellAtlas/HLCA_reproducibility#15]
Hello all,
I would like to use the metacells algorithm https://github.com/tanaylab/metacells to aggregate the cells to 'pseudo cells'. To run metacells, I need raw (integer) counts that are not corrected for sampling depth. In adata.raw.X, I find those integer counts, however, I am not sure whether these are SCANVI corrected or not - they are not, right?
Thank you so much for your support,
enjoy the holidays!

**Comment by LisaSikkema** [comment]
Hey @annaKett, so sorry for the late reply (currently on maternity leave). The counts are indeed not corrected!
