### ISSUE TITLE
Where to find cell-level metadata for extended HLCA datasets

### ISSUE THREAD

**Issue by emdann** [LungCellAtlas/HLCA_reproducibility#3]
Hi @LisaSikkema
I would like to use the mapped embeddings for one of the datasets in the extended HLCA (the `Kaminski_2020` dataset). I've managed to download trained models and embeddings from Zenodo, but the AnnData object contains no info in `.obs`. I mainly need sample-level metadata (such and donor or disease status) and ideally also cell-type annotations (either from original authors or from label transfer). Is this info available somewhere? Or should I go back to the original publication?
Thanks in advance!

**Comment by LisaSikkema** [comment]
Hey Emma! 
Good question, those things are a little bit spread out over the internet right now ;) we will publish the full extension, including all counts and all metadata together with the final publication.
However, for now you can already find all the metadata you need in the 2000 highly variable genes version of the extended HLCA on FASTgenomics:
https://beta.fastgenomics.org/datasets/detail-dataset-427f1eee6dd44f50bae1ab13f0f3c6a9#Files
Under `HLCA_v1_extended_raw_counts_2000hvgs.h5ad`. 
Let me know if that has what you need!

**Comment by emdann** [comment]
Thanks for the quick reply Lisa! I think the FASTgenomics object has all I need for now :)
