### ISSUE TITLE
Meyer 2021 Mapped Cell types

### ISSUE THREAD

**Issue by Yanay1** [LungCellAtlas/HLCA_reproducibility#6]
Is it possible to add a CSV of the original cell types for Meyer 2021 that were compared to the model predictions:

"Overall, the transferred labels were correct in the majority of cases, with 69% of the cells correctly labeled, 12% of labels incorrect, and 18% set to “unknown”"

Thanks!

**Comment by LisaSikkema** [comment]
Hi @yanay1, 
The original annotations should be available in the [downloadable object](https://beta.fastgenomics.org/datasets/detail-dataset-427f1eee6dd44f50bae1ab13f0f3c6a9#Files), (file "HLCA_v1_extended_raw_counts_2000hvgs.h5ad") under `adata.obs.original_ann_nonharmonized`.
We are working on getting the up-to-date version of the extended atlas (generated during revisions, it has slightly altered annotations in the HLCA core and in the Meyer_2021 data) ready for sharing, it should be done soon. 

We then mapped those original annotations to our "harmonized cell type reference" according to [this table](https://github.com/LungCellAtlas/HLCA_reproducibility/blob/main/supporting_files/metadata_harmonization/HLCA_cell_type_reference_mapping_20221007.csv).

Finally, in [this notebook](https://github.com/LungCellAtlas/HLCA_reproducibility/blob/main/notebooks/3_atlas_extension/06_Meyer_2021_label_transfer_analysis.ipynb) you can find how we dealt with new cell types and or differences in granularity between the HLCA core and the mapped data, and how we calculated those final percentages (see the header "Label matching between query and reference"). 

These are the latest tables and notebooks (i.e. updated here and there for the revisions), so they will not match the h5ad file above perfectly. I can share the up-to-date h5ad with you via email if you'd like, or you can wait a bit more and it should be up on cellxgene soon. 

Let me know if that helps!

**Comment by Yanay1** [comment]
Thanks so much! It would be great to see the up to date h5ads! I can be reached on email at yanay@stanford.edu.

I have an additional question about how the labels were transferred to the meyer 2021 data: were the meyer 2021 annotations used during architecture surgery?

Thanks!

**Comment by LisaSikkema** [comment]
Okay will send you an email!
No, for surgery we never used annotations, all cells were set to "unlabelled"

**Comment by LisaSikkema** [comment]
Maybe helpful, here's the dictionary specifying the matching of query and reference labels, for assessing correct/incorrect/unknown transferred labels: (transferred labels with uncertainty > 0.3 were set to unknown for this analysis)
```python
{'AT1': ['AT1'],
 'Plasma cells': ['Plasma cells'],
 'Non-classical monocytes': ['Non-classical monocytes'],
 'Interstitial Mph perivascular': ['Interstitial Mph perivascular'],
 'AT2': ['AT2'],
 'Alveolar macrophages': ['Alveolar macrophages'],
 'Adventitial fibroblasts': ['Adventitial fibroblasts'],
 'Classical monocytes': ['Classical monocytes'],
 'AT2 proliferating': ['AT2 proliferating'],
 'EC aerocyte capillary': ['EC aerocyte capillary'],
 'Plasmacytoid DCs': ['Plasmacytoid DCs'],
 'DC2': ['DC2'],
 'Mast cells': ['Mast cells'],
 'SMG mucous': ['SMG mucous'],
 'DC1': ['DC1'],
 'EC general capillary': ['EC general capillary'],
 'EC venous systemic': ['EC venous systemic'],
 'Myofibroblasts': ['Myofibroblasts'],
 'EC venous pulmonary': ['EC venous pulmonary'],
 'Alveolar fibroblasts': ['Alveolar fibroblasts'],
 'Pericytes': ['Pericytes'],
 'Peribronchial fibroblasts': ['Peribronchial fibroblasts'],
 'Alveolar Mph MT-positive': ['Alveolar Mph MT-positive'],
 'Monocyte-derived Mph': ['Monocyte-derived Mph'],
 'Suprabasal': ['Suprabasal'],
 'Alveolar Mph CCL3+': ['Alveolar Mph CCL3+'],
 'Mesothelium': ['Mesothelium'],
 'Migratory DCs': ['Migratory DCs'],
 'Neuroendocrine': ['Neuroendocrine'],
 'SMG duct': ['SMG duct'],
 'Deuterosomal': ['Deuterosomal'],
 'Lymphatic EC': ['Lymphatic EC mature',
  'Lymphatic EC proliferating',
  'Lymphatic EC differentiating'],
 'Multiciliated': ['Multiciliated (nasal)', 'Multiciliated (non-nasal)'],
 'Club': ['Club (non-nasal)', 'Club (nasal)'],
 'Interstitial macrophages': ['Monocyte-derived Mph',
  'Interstitial Mph perivascular'],
 'Goblet': ['Goblet (nasal)', 'Goblet (bronchial)', 'Goblet (subsegmental)'],
 'Basal': ['Basal resting', 'Suprabasal', 'Hillock-like'],
 'Rare': ['Ionocyte', 'Tuft', 'Neuroendocrine'],
 'SMG serous': ['SMG serous (nasal)', 'SMG serous (bronchial)'],
 'CD8_EM/EMRA': ['CD8 T cells'],
 'CD8 T cells EM': ['CD8 T cells'],
 'NK CD11d': ['NK cells'],
 'CD4 T cells EM': ['CD4 T cells'],
 'NK CD16': ['NK cells'],
 'CD8_TRM/EM': ['CD8 T cells'],
 'CD4T cells TRM': ['CD4 T cells'],
 'CD4 T cells naive': ['CD4 T cells'],
 'Vascular smooth muscle': ['Smooth muscle'],
 'Memory B cells': ['B cells'],
 'Arterial Systemic': ['EC arterial'],
 'Arterial Pulmonary': ['EC arterial'],
 'CD8 T cells TRM': ['CD8 T cells'],
 'Naive B cells': ['B cells'],
 'NK CD56': ['NK cells'],
 'Plasmablasts': ['Plasma cells'],
 'Airway smooth muscle': ['Smooth muscle'],
 'Erythrocytes': ['New'],
 'Basal proliferating': ['Basal resting', 'Suprabasal'],
 'Schwann myelinating': ['New'],
 'Gamma-delta T cells': ['New'],
 'Megakaryocytes': ['New'],
 'NKT cells': ['New'],
 'Chondrocytes': ['New'],
 'Regulatory T cells': ['New'],
 'ILCs': ['New'],
 'SMG basal A': ['New'],
 'MAIT cells': ['New'],
 'Mph proliferating': ['Alveolar Mph proliferating',
  'Interstitial Mph perivascular',
  'Monocyte-derived Mph',
  'Alveolar macrophages'],
 'Schwann nonmyelinating': ['New'],
 'Nerve-associated fibroblasts': ['New'],
"Macrophages SPP1 high": [
        "Alveolar Mph proliferating",
        "Interstitial Mph perivascular",
        "Monocyte-derived Mph",
        "Alveolar macrophages",
    ]}
 ```
 This dictionary is now also printed in the Jupyter notebook I linked to previously.

I moreover added a table to the results that has the detailed information with original non-harmonized labels, original harmonized labels, and transferred labels per cell for the meyer data. It is included in the full results folder, which can be downloaded as now explained in [this text file](https://github.com/LungCellAtlas/HLCA_reproducibility/blob/main/results_download.txt). 

I also post the csv here, so that you don't need to download the full results folder:
[meyer_label_transfer_detailed.csv](https://github.com/LungCellAtlas/HLCA_reproducibility/files/10411604/meyer_label_transfer_detailed.csv)
You might have to rework the barcodes a bit to match with your own, as we added a suffix for every dataset in the HLCA to prevent barcode duplicates.

I hope this helps! I will close the issue for now but feel free to re-open.

**Comment by LisaSikkema** [comment]
@jan-engelmann discovered a small mistake in the mapping, `'Macrophages SPP1 high': ['Macrophages']` should have been 
```
 "Macrophages SPP1 high": [
        "Alveolar Mph proliferating",
        "Interstitial Mph perivascular",
        "Monocyte-derived Mph",
        "Alveolar macrophages",
    ]
```
This is now fixed in the notebook (with brief explanation), and I edited the dictionary above to correct that, as well as the csv included in the post above.
