### ISSUE TITLE
Can't download results folder

### ISSUE THREAD

**Issue by Yanay1** [LungCellAtlas/HLCA_reproducibility#8]
Hello! I am trying to follow the instructions in 

https://github.com/LungCellAtlas/HLCA_reproducibility/blob/main/results_download.txt 

But the download link is not loading. Thanks!

**Comment by LisaSikkema** [comment]
Hey @Yanay1,

That could be right, our institute got hacked a few weeks ago and many of our servers are still down at the moment, we cannot access most of our files. We are hoping this will be resolved very soon (maybe within a week) but aren't sure at all. You can try again in some time or send me a reminder here, I will try to remember to give you a heads up once the servers are up again. 

Sorry for the trouble!

**Comment by LisaSikkema** [comment]
Hey @Yanay1 , it took quite a while but our file sharing server is back up again. Could you try and see if you're able to download the results folder now?

**Comment by Yanay1** [comment]
Yes this appears to work, thanks so much!
